Test shokhjakhon
Shohjahont9/Delivery_Takeout pull request #2
Opened 2022-01-24 08:05 UTC by Shohjahont9

2022-01-25 10:12 UTC, NikitaLychkovski requested changes

2022-01-25 10:12 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/utils/Extension.kt
> +    val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.getDefault())
DateUtils.kt why did you put it here?

2022-01-25 10:12 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/utils/Extension.kt
> +    return (this.toInt() / 60).toString()
for such function is better to add an exception check toInt() not sage

2022-01-25 10:12 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/utils/Extension.kt
> +fun View.visible(isVisible: Boolean) {
function should start with verb, so better to rename to isVisible

2022-01-25 10:12 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/presentation/mainScreen/GetCardsAdapter.kt
> +class GetCardsAdapter : RecyclerView.Adapter<GetCardsAdapter.GetCardViewHolder>() {
only functions should have a verb in the start of the name, so it is better to change the name to CardsAdapter/KitchenCardsAdapter

2022-01-25 10:12 UTC, NikitaLychkovski commented on app/src/main/res/layout/fragment_main_screen.xml
> +        android:text="CURRENT ORDERS (23)"
All strings that are hardcoded here should be put in XML strings

2022-01-25 10:33 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/presentation/mainScreen/GetCardsAdapter.kt
> +                when (data.status) {
Please, make this status ENUM. It is not safe to work with this as strings

2022-01-25 12:01 UTC, Shohjahont9 commented on app/src/main/java/uz/larsLion/deliverytakeout/utils/Extension.kt
> +    val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.getDefault())
In order to change "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" format to "HH-mm"

2022-01-25 12:01 UTC, Shohjahont9 commented on app/src/main/java/uz/larsLion/deliverytakeout/utils/Extension.kt
> +    return (this.toInt() / 60).toString()
Okay :)

2022-01-25 12:04 UTC, Shohjahont9 commented on app/src/main/java/uz/larsLion/deliverytakeout/presentation/mainScreen/GetCardsAdapter.kt
> +                tvTime.text = data.preparationTime.toString().secToMin()+"m"?:""
you mean, context.getString(R.string.m) ?

2022-01-31 09:17 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/data/repository/KitchenCardRepositoryImp.kt
> +    }
Here in this project is okay. But in the case of a real data source, you need to think about updating of cache. Cause imagine you load data once. Your repository is single so it will exist until your app is running. And when new order will come, you never receive it in app. Unit you restart it

2022-01-31 09:17 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/data/source/remote/responseData/KitchenCardItem.kt
> +    @SerializedName("unavailabilityReason") val unavailabilityReason: String
```suggestion
    @SerializedName("cardId") 
    val cardId: String,
    @SerializedName("cardItemId")
    val cardItemId: String,
    @SerializedName("createdAt") 
    val createdAt: Int,
    @SerializedName("description") 
    val description: String,
    @SerializedName("isAvailable") 
    val isAvailable: Boolean,
    @SerializedName("itemId") 
    val itemId: String,
    @SerializedName("lastUpdatedAt") 
    val lastUpdatedAt: Int,
    @SerializedName("name") 
    val name: String,
    @SerializedName("orderId") 
    val orderId: String,
    @SerializedName("orderItemId") 
    val orderItemId: String,
    @SerializedName("orderShortId") 
    val orderShortId: Int,
    @SerializedName("pickupTime") 
    val pickupTime: String,
    @SerializedName("preparationTime") 
    val preparationTime: Int,
    @SerializedName("profileIds") 
    val profileIds: List<String>? = null,
    @SerializedName("quantity") 
    val quantity: Int,
    @SerializedName("routing") 
    val routing: List<String>,
    @SerializedName("scheduledFor") 
    val scheduledFor: String,
    @SerializedName("seatNumbers") 
    val seatNumbers: String?,
    @SerializedName("status") 
    val status: String,
    @SerializedName("tableName") 
    val tableName: String,
    @SerializedName("tableNumbers") 
    val tableNumbers: Int?,
    @SerializedName("unavailabilityReason") 
    val unavailabilityReason: String
```

2022-01-31 09:17 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/presentation/mainScreen/MainScreenFragment.kt
> +        with(_binding!!) {
Still, you should not use `!!` at all. Even if you 100% sure. Here if you change
`        _binding!!.addItem.setColorFilter(Color.WHITE) 
`
to
`        _binding?.addItem.setColorFilter(Color.WHITE)
`
noting will change in behavior but you will be null pointer exceptions save

2022-01-31 09:17 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/presentation/mainScreen/MainScreenFragment.kt
> +        _binding!!.rvOrder.apply {
same here remove `!!`

2022-01-31 09:17 UTC, NikitaLychkovski commented on app/src/main/java/uz/larsLion/deliverytakeout/utils/Extension.kt
> +    val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.getDefault())
I mean that you have already created some object in DateUtils.yyyy_mm_dd_hh_mm_ss_z it is better to reuse it much as possible then

2022-02-03 05:06 UTC, Shohjahont9 commented on app/src/main/java/uz/larsLion/deliverytakeout/presentation/mainScreen/MainScreenFragment.kt
> +        with(_binding!!) {
understood

2022-02-03 05:32 UTC, merged